lua/no-neck-pain/main.lua
fixes https://github.com/shortcuts/no-neck-pain.nvim/issues/20
`WinClosed` is not triggered when using `:bd`, which may leave NNP buffers open.
=> fix: NNP disabling not triggering

README.md, lua/no-neck-pain/init.lua, plugin/no-neck-pain.lua, tests/test_API.lua
It is not possible for NNP to support `dashboard-nvim`, as it does not support split/vsplit buffers. We can however provide better snippets on how to automate the NNP enablement with dashboard support.
=> chore: better snippets for dashboard support

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, tests/test_API.lua, tests/test_side_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/18
this allow an easy way to exclude NNP buffers from buffer list if needed
=> feat: named side buffer

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua
=> chore: make README usage more straight forward

doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util.lua, tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/20
Provide an option to disable NNP if the last buffer has been closed, the check is ugly but should be refactored in https://github.com/shortcuts/no-neck-pain.nvim/issues/35
=> feat: add `disableOnLastBuffer` option

doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/36
we previously closed all buffers except the main one when disabling NNP, it's unexpected but worth leaving it configurable.
=> feat: add `killAllBuffersOnDisable` option

lua/no-neck-pain/main.lua, lua/no-neck-pain/util.lua
follow up of https://github.com/shortcuts/no-neck-pain.nvim/pull/41
side buffers were killed by the `only` command, but left open with `killAllBuffersOnDisable` as `false`.
=> fix: side buffers not closing when `killAllBuffersOnDisable` is false

lua/no-neck-pain/util.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/46
we don't need to force, if it does not exist then it will be skipped.
=> fix: prevent force close window

lua/no-neck-pain/main.lua, lua/no-neck-pain/util.lua, tests/test_API.lua
- Prevent triggering an error when trying to close the last buffer with NNP enabled
- Better debug logging
- Properly reset augroup
=> fix: prevent error on last buffer close

lua/no-neck-pain/main.lua, tests/test_side_buffers.lua
Replacing the event `BufWinEnter` with `WinEnter` will add support for a split command, which opens the same buffer in a new window. Now, when you do `<c-w>v` or `<c-w>s` it will hide side buffers as well.
=> feat: support same buffer splits

doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, tests/test_API.lua
This PR adds a new option for the side buffers to configure the background color.
The goal is not to provide some theme features in NNP, but to make the side buffer "blend" in the user's theme.
The option supports hexadecimal codes, but the end goal is to provide aliases for popular integration such as:
| with value `catppucin-frappe` | with arbitrary value |
|:---------:|:---------:|
| <img alt="Screenshot 2022-12-16 at 22 34 35" src="https://user-images.githubusercontent.com/20689156/208194828-bbd8ed3b-8321-4cd3-a873-4d9c7c7c5ba9.png"> | <img alt="Screenshot 2022-12-17 at 10 26 52" src="https://user-images.githubusercontent.com/20689156/208235401-672183aa-42a5-4c7e-a1a3-00ffc9b5960e.png"> |
=> feat: allow customizing bg color of side buffers

lua/no-neck-pain/util/color.lua
There was some missing blocks in the color group
|Before|After|
|---|---|
| <img width="1280" alt="Screenshot 2022-12-17 at 22 49 35" src="https://user-images.githubusercontent.com/20689156/208267183-2c848980-4f75-4a16-b980-56ae41df956d.png"> | <img width="1280" alt="Screenshot 2022-12-17 at 22 39 09" src="https://user-images.githubusercontent.com/20689156/208267185-a21ed247-7076-4b49-b226-74c68b6d0f2b.png"> |
=> fix: color leaving non-colored blocks

lua/no-neck-pain/init.lua
This unused var causes the config to reset its state.
=> fix: prevent config reset

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, lua/no-neck-pain/util/debug.lua
=> fix: highlight group typo

lua/no-neck-pain/main.lua, lua/no-neck-pain/util/win.lua, tests/test_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/62
Closing a side buffer without any other valid window open now quits Neovim (e.g. closing `curr` but there's no other active window left). If we close a side buffer but `curr` or `split` is still there, we will just disable NNP.
=> fix: quit Neovim when killing one of the last NNP buffer

.gitignore, lua/no-neck-pain/main.lua, tests/test_API.lua, tests/test_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/42
This PR prevents creating side buffers when there's not enough space on the screen to do it, it also re-creates them if the window is resized.
=> feat: close side buffers when no space left

lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua
`setup`-less calls might fail due to missing default values, we now define them when calling the toggle method, if it's not the case already.
=> fix: make setup-less easier

Makefile, README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/win.lua, scripts/minimal_init.lua, scripts/minitest.lua, tests/helpers.lua, tests/test_API.lua, tests/test_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/77
This update aims at making NNP correctly resize its side buffers when there's a side tree that opens, or is already opened.
The internal state API have been rewrote to store `external` window values (e.g. tree). it doesn't change how NNP works at all, but should be less verbose.
=> feat: handle side tree

.gitignore, README.md, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, tests/test_API.lua, tests/test_buffers.lua
As discussed in #76, the exposed options have been refactored to allow more customization of the side buffers. We now provide:
- `common`: defines options common to both buffers
- `left`/`right`: defines options for the side buffer directly
=> feat!: refactor setup

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/util/color.lua, tests/test_API.lua
The editor background uses the `base` color of the palette, as defined [here](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/groups/editor.lua#L32). Currently the `crust` values are being used, making the side buffers darker than the main window.
We now provide both color themes.
- [Frappe](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/frappe.lua#L32)
- [Latte](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/latte.lua#L32)
- [Macchiato](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/macchiato.lua#L32)
- [Mocha](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6 …
=> fix: adjust catppuccin colors to the correct values

lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/util/win.lua, tests/test_API.lua
We were not correctly spreading the common table in the `left` or `right` ones, which led to non-forwarded options.
=> fix: prevent `setup` wrong overrides

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/util/win.lua, tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/90
follow up of https://github.com/shortcuts/no-neck-pain.nvim/pull/78
I was bothered by the fact that the next breaking change of the API would introduce a `common` field instead of being at the root of the `buffers`. The goal is to make it even easy to use and configure the plugin.
=> feat(config): cleanup fields and unused code

lua/no-neck-pain/main.lua, tests/test_API.lua, tests/test_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/81
a normal split won't disable NNP during the split anymore, which wasn't an expected behavior. This prevents big UI shift when opening splits.
Vsplits are unchanged.
`vsplit`:
`split`:
`split` and `vsplit`:
=> feat: prevent split closing side buffers

lua/no-neck-pain/main.lua, lua/no-neck-pain/util/win.lua
https://github.com/shortcuts/no-neck-pain.nvim/pull/92 introduced an error which impacted the opening of vsplit windows, due to wrong computation, windows like Packer were overlapping.
This is now much more reliable since we now consider side buffers.
=> fix: split/vsplit computing

lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, lua/no-neck-pain/util/debug.lua, lua/no-neck-pain/util/win.lua, tests/test_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/82
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/99
The goal is to split hooks responsibilities to prevent unwanted behaviors. This PR also covers wrong interpretation of a `BufDelete` event.
=> feat: reduce number of resize event

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/win.lua, tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/94
This PR adds support for undotree, to prevent UI shifts. It also makes the internal state API much more extensible, for next integration support.
Undotree
NvimTree
=> feat: support undotree

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/util/color.lua, tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/72
=> feat: add `blend` value to brighten/darken color background

lua/no-neck-pain/main.lua, lua/no-neck-pain/util/map.lua, tests/test_buffers.lua
Seems like the Close/Delete hook is triggered when entering a help window. To prevent this, we ensure at least one NNP win is missing from the win list before entering the split/vsplit closing logic.
Someone, this happened only when having a single side buffer.
=> fix: prevent help split disabling nnp

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, scripts/test_auto_open.lua, tests/test_API.lua
The `enableOnVimEnter` creates an autocmd, when calling the `setup` method, which will enable the plugin when entering Neovim.
The end option should accept `true | false | callback` so the user can control whether or not it should be enable (e.g. when opening a dashboard, or nvim-tree)
=> feat: add `enableOnVimEnter` option

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, tests/test_API.lua
Now that we have text color for side buffers, it would be annoying to require extra options on the user side. 
Side buffers are now scratch pad by default, it doesn't change their look but allow us to write in it
=> feat: make side buffer a scratch pad

lua/no-neck-pain/init.lua, lua/no-neck-pain/util/event.lua
Now that we have an Enter hook to automatically enable the plugin, we can introduce plugin-related behaviors to prevent conflicting with others.
=> feat: add built-in nvim-tree and dashboard support

lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/util/win.lua, tests/test_buffers.lua
discovered in https://github.com/shortcuts/no-neck-pain.nvim/pull/113, closes https://github.com/shortcuts/no-neck-pain.nvim/issues/125
we now use the proper command to open side buffers at the left/right most of the screen.
**Before**
**After**
=> fix: weird layout when enabling the plugin with vsplit(s) opened

doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/color.lua, lua/no-neck-pain/util/event.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/73
we can default the text color to the background one, plus some blending, to ease the usage of those features.
We default to blend +0.5 which should work in most cases.
=> feat: default text color

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/util/trees.lua, lua/no-neck-pain/util/win.lua
discovered in https://github.com/shortcuts/no-neck-pain.nvim/pull/134, we triggered some events when entering side buffers, while those should be "transparent" to the user.
=> fix: prevent unwanted event trigger

plugin/no-neck-pain.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/137
the method used to register the command is only available in Neovim 0.7 and higher, this should cover older versions.
=> fix: register command for nvim <0.7

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/util/win.lua, tests/test_API.lua, tests/test_buffers.lua, tests/test_colors.lua, tests/test_integrations.lua, tests/test_scratchpad.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/121
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/122
This PR adds a built-in scratch pad feature, which leverages side buffers to read/write to file of choice.
When enabled (false by default), side buffers will be created with the following options:
- `bufhidden` ""
- `buftype` ""
- `autoread` true
- `autowriteall` true
The location is configurable in case the user don't want to have the scratchpad pushed to git or something.
The filetype is defaulted to `norg`, but can be changed via the `bo` options.
-----
with config:
```lua
require("no-neck-pain").setup({
debug = true,
width = 80,
enableOnVimEnter = true,
toggleMapping = "<Leader>kz",
buffers = {
backgroundColor = "onedark",
blend = -0.1,
scratchPad = { …
```
=> feat: add built-in scratchpad

lua/no-neck-pain/util/win.lua, tests/test_scratchpad.lua
scratchpad buffers shouldn't be listed, as they shouldn't alter the user workflow.
=> fix: set scratchpad buffers as `unlisted`

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/util/win.lua, tests/test_API.lua, tests/test_integrations.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/133
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/142
The width of the tree was still taken into account with the `reopen = false` option. We now reset the registered trees width before computing the padding, if `reopen` is `false`.
The `close` option doesn't make sense actually, we close it anyway, a single option is enough.
=> fix: wrong size buffer width with NvimTree

lua/no-neck-pain/main.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/util/split.lua, lua/no-neck-pain/util/tabs.lua, lua/no-neck-pain/util/trees.lua, lua/no-neck-pain/util/win.lua, tests/test_API.lua, tests/test_autocmd.lua, tests/test_buffers.lua, tests/test_scratchpad.lua, tests/test_split.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/89
This PR is a first step of the tabs support, it allows restoring the state correctly when executing `tabprevious`, so the side buffers are not closed.
State-per-tab will be followed in https://github.com/shortcuts/no-neck-pain.nvim/issues/152
=> feat: keeps side buffers for current tab

README.md, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, plugin/no-neck-pain.lua, tests/test_API.lua, tests/test_commands.lua
Kind of provides an escape hatch for things like https://github.com/shortcuts/no-neck-pain.nvim/issues/155
This PR provides a new `NoNeckPainResize` command, that updates the width of the main buffer and triggers a resize of the windows. This can be useful when switching context and the user don't want to update the `setup` method.
=> feat: add `NoNeckPainResize` command

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/color.lua, lua/no-neck-pain/config.lua
fixes https://github.com/shortcuts/no-neck-pain.nvim/issues/120
fixes https://github.com/shortcuts/no-neck-pain.nvim/issues/104
The plugin generates unwanted white lines on transparent backgrounds, we now keep the default Neovim behavior.
bonus: easier to maintain syntax
Before: https://github.com/shortcuts/no-neck-pain.nvim/issues/120#issue-1518599089
After
=> fix: transparent background support

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, scripts/test_auto_open.lua, tests/test_API.lua, tests/test_tabs.lua
Now that we have tabs support, we can provide a way to automatically enable the plugin when entering a new tab, similarly to when entering Neovim.
=> feat(tabs): provide an option to automatically enable the plugin

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/wins.lua, tests/test_API.lua, tests/test_split.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/161
Side buffer can create visual noise when there's not enough space to create them (e.g. if the width is 1..5), see image 1.
With this PR, we now do not create side buffers if they don't have a width > 5, an option have also been exposed to let the user override this default value.
=> feat: add `minSidebufferWidth`

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/tabs.lua, lua/no-neck-pain/util/event.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/174
partially https://github.com/shortcuts/no-neck-pain.nvim/issues/175
Toggling a side tree did not properly triggered a resize due to a strict check on the currently opened windows, we now loose this hook a bit to trigger a resize when closing the window, this allows us to increase consistency of the side buffers width.
=> fix: wrong side buffer width when toggling NvimTree

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/wins.lua, tests/test_API.lua, tests/test_split.lua
technically not a breaking change since it's not yet released, but this PR renames `minSidebufferWidth` to `minSideBufferWidth` for camel casing consistency..
=> fix: `minSidebufferWidth` casing

lua/no-neck-pain/color.lua, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, tests/test_API.lua, tests/test_colors.lua
This PR allow to use the `blend` option without specifying a custom background color.
We now also move the responsibility of setting the config background colors to the parsing method, this allow to test transparent backgrounds but also seems more correct.
=> feat: support `blend` without background color

lua/no-neck-pain/wins.lua, tests/test_buffers.lua
With `setNames=true`, toggling the plugin at least twice result in the following error:
```
FAIL in tests/test_buffers.lua | left/right | setNames doesn't throw when re-creating side buffers: Vim:Error executing Lua cal
lback: ...lm/Documents/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:76: Vim:E95: Buffer with this name already exists
stack traceback:
[C]: in function 'nvim_buf_set_name'
...lm/Documents/no-neck-pain.nvim/lua/no-neck-pain/wins.lua:76: in function 'createSideBuffers'
...lm/Documents/no-neck-pain.nvim/lua/no-neck-pain/main.lua:44: in function 'init'
...lm/Documents/no-neck-pain.nvim/lua/no-neck-pain/main.lua:77: in function 'toggle'
...lm/Documents/no-neck-pain.nvim/lua/no-neck-pain/init.lua:11: in function 'toggle' …
```
=> fix: prevent duplicate buffer name error with `setNames`

lua/no-neck-pain/color.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/184
pretty much a dumb error, the internal `matchAndblend` method returns the given color in lower case, which led to a casing issue when comparing with `NONE` instead of `none`
=> fix: textColor blending

lua/no-neck-pain/main.lua, lua/no-neck-pain/wins.lua
Closing the main window with other vsplits and splits open constantly result in a wrongly focused window (on a side buffer).
This PR now properly restore the focus.
=> fix: wrong focus when closing the main window

lua/no-neck-pain/util/debug.lua, lua/no-neck-pain/wins.lua, tests/test_split.lua
Opening vsplit windows while having **only one side buffer** opened might result in wrongly size panes, this is because the side buffers are resized **after** the split have been opened. 
We now resize all opened vsplit for this case.
before
after
=> fix: vsplit wrongly sized

README.md, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/color.lua, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, lua/no-neck-pain/util/debug.lua, scripts/test_auto_open.lua, tests/test_API.lua, tests/test_colors.lua, tests/test_mapping.lua, tests/test_scratchpad.lua
This PR introduces the v1.0.0 of the plugin, which comes with several breaking changes at the API level.
The plugin evolved fast but some part of the API are not extensible enough to continue the iteration, this much needed breaking change allow future features to be added without having to break the it again.
------
|   Before   |         After        |
|-------------|----------------------------|
|`enableOnVimEnter`|`autocmds.enableOnVimEnter`|
|`enableOnTabEnter`|`autocmds.enableOnTabEnter`|
|`toggleMapping`|`mappings.toggle`|
|`widthUpMapping`|`mappings.widthUp`|
|`widthDownMapping`|`mappings.widthDown`|
|`backgroundColor`|`colors.background`|
|`textColor`|`colors.text`|
|`blend`|`colors.blend`|
|`left.backgroundColor`|`left.colors.background`|
|`left.textColor`|`left.colors.text`| …
=> feat!: v1.0.0 - API breaking changes

lua/no-neck-pain/main.lua, lua/no-neck-pain/trees.lua, lua/no-neck-pain/wins.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/191
This PR kind of fixes all integrations, where we were constantly polling for side trees which could lead to performance issues (maybe contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/171)
NeoTree in particular was broken due to the filetype having a different name than the integration, which led to non-registered windows, and therefore wrongly sized buffers (see closes https://github.com/shortcuts/no-neck-pain.nvim/issues/191)
=> fix: side trees infinite polling

lua/no-neck-pain/trees.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/212
leverages new commands deprecated of outdated ones
=> fix: leverage new Neotree commands

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/splits.lua, lua/no-neck-pain/tabs.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/wins.lua, tests/test_API.lua, tests/test_splits.lua
This PR aims at fixing some wrongly resized vsplit panes with side buffers open. It also makes the state much more consistent, same as determining which kind of split action have been done.
=> refactor: split/vsplit state manager and fix weird resizes

Makefile, lua/no-neck-pain/main.lua, scripts/init_auto_open.lua, scripts/init_with_deps.lua, tests/helpers.lua, tests/test_API.lua, tests/test_autocmds.lua, tests/test_buffers.lua, tests/test_mappings.lua, tests/test_scratchpad.lua, tests/test_splits.lua, tests/test_tabs.lua
entering a new vsplit/split window that is not the currently focused window doesn't register the split, which can end up in unwanted layout issue.
we now consider any non registered window in the vsplit/split handler
=> fix: register unfocused splits

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/colors.lua, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, lua/no-neck-pain/util/debug.lua, lua/no-neck-pain/wins.lua, tests/test_colors.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/222
provides an autocmd that the user can enable in order to refresh the configuration when changing the colorscheme.
=> fix: refresh colorscheme

lua/no-neck-pain/main.lua, lua/no-neck-pain/tabs.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/wins.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/229
There's a synchronization issue with the tab state on `TabLeave` events, which ends up in invalid IDs when navigating through tab windows.
This PR provides a new way of synchronizing state on `TabLeave` and `NoNeckPain.disable` events, however it highlights an other issue with closed tabs left in state, which will be tackled in https://github.com/shortcuts/no-neck-pain.nvim/issues/230
=> fix: tab state synchronization

lua/no-neck-pain/main.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/230
if the `augroup` is already deleted, we don't want to throw an error.
=> fix: prevent error on augroup deletion

.github/workflows/main.yml
=> chore: run CI on nvim 0.9.1

lua/no-neck-pain/main.lua, lua/no-neck-pain/tabs.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/230
this PR prevents unsynchronized state with closed tabs.
=> fix: remove closed tab from state

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/tabs.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/wins.lua
relying on a copy of the current state tab indeed prevent race conditions, but makes it harder to manage state updates.
this new approach makes it more reliable to work on the state.
=> fix(internal): prevent unsync state

.github/workflows/main.yml
=> chore: bump neovim on CI

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/wins.lua, tests/test_integrations.lua
resize is triggered when there shouldn't be, this pr fixes an unwanted event trigger
=> fix(event): prevent unwanted resize

lua/no-neck-pain/main.lua
with the plugin enabled, resizing nvim when focus is on a relative window (e.g. telescope), breaks the state as we skip the resize event.
we now consider it.
=> fix(resize): do not skip `VimResized` event

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, plugin/no-neck-pain.lua, tests/test_commands.lua, tests/test_mappings.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/261
this pr allows the user to define a custom value for the widthUp and widthDown mapping, because the default value (5) might be too little for some screens
=> feat(mappins): allow custom values for widthUp and widthDown

README.md, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, plugin/no-neck-pain.lua, tests/test_API.lua, tests/test_commands.lua, tests/test_mappings.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/262
this pr exposes two new commands named `NoNeckPainToggleLeftSide` and `NoNeckPainToggleRightSide` which allows the user to toggle a side window.
=> feat(api): add commands to toggle sides

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/wins.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/268
this pr tries to prevent unsynced state when adding/removing/switching tabs
=> fix(tabs): prevent unsynced state in tab switchs

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/util/event.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/268 (again)
we were relying on a default (and wrong) initial `activeTab` value which was set to 1. While working properly when enabling on the tab 1, then the others, it broke when we were initializing the plugin at a tab index other than 1.
we now rely on an helper than ensures the `activeTab` comes from the neovim state and not hardcoded.
=> fix(tabs): prevent wrong activeTab index

Makefile, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/273
the state doesn't really know which tab is the active one since we edit the state **before** leaving a tab.
this PR focuses on splitting concerns by handling the inactive tab cleanup at the `TabLeave` event time, while updating the active tab state at the `TabEnter` event level.
also fixes the refresh tab method which was messing up the order of the map by shifting everything at the first position
=> fix(tabs): prevent unsynchronized state on toggle

Makefile, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/wins.lua, tests/helpers.lua, tests/test_autocmds.lua, tests/test_options.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/243 https://github.com/shortcuts/no-neck-pain.nvim/issues/280
because `:bd` closes the window the buffer is attached to, we need to provide a custom way to fallback to an other window. As of now, the solution is opt-in because it might not be perfect, but should still cover many use cases.
In order to use this feature, a user must set `fallbackOnBufferDelete = true`
=> feat(api): support :bdelete

.gitignore, Makefile, lua/no-neck-pain/colors.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, tests/test_colors.lua
Add namespaces to highlight groups and use local scopes in order to prevent impacting other buffers
=> fix(hl): prevent global highlights

doc/no-neck-pain.txt, lua/no-neck-pain/colors.lua, lua/no-neck-pain/main.lua, tests/test_API.lua, tests/test_colors.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/286
We were setting highlight groups even when no configuration was provided, which created some discrepancies in case we were not correctly retrieving the variable, or if the theme changed during the nvim lifecycle. 
we now only create highlight groups if the user provide some colors configuration
=> fix(hl): prevent wrong bg and text colors after `:bd`

Makefile, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/colors.lua, lua/no-neck-pain/config.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/wins.lua, tests/test_integrations.lua, tests/test_scratchpad.lua
The buffer and window options are not properly forward to the scratchPad when setting it as `enabled`. We now change the order of definition in order to prevent overwriting them.
=> fix(scratchPad): properly forward buffer/window options

lua/no-neck-pain/colors.lua
add `StatusLine` and `StatusLineNC` highlights
=> feat(theme): add StatusLine and StatusLineNC highlights to the group

lua/no-neck-pain/wins.lua, tests/test_scratchpad.lua
The default and/or user defined buffer/window options override the scratchPad options, which makes the buffer uneditable when it's enabled
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/295
=> fix: buffer options order

lua/no-neck-pain/config.lua, lua/no-neck-pain/wins.lua, tests/test_scratchpad.lua
The fix from commit [fdbd8bf](https://github.com/shortcuts/no-neck-pain.nvim/commit/fdbd8bf4790389fd9d97aa1b14c6c5488bfb5c87) wasn't actually fixing the issue. After some debugging I believe this approach is the most correct i.e.: in case user wants to use scratch pad - update the default config values instead of overwriting them manually in the function.
n/a
=> fix(scratchPas): set default options at config init

lua/no-neck-pain/state.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/wins.lua, tests/test_integrations.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/258
we can reduce the debounce to 30ms without impacting TSPlayground, 5ms works for any other integrations but needs more investigation
also fix an issue where toggling a `right` integration with only a `left` padding enabled doesn't resize the split, and vice-versa
=> fix(integrations): faster debounce and resize padding

Makefile, doc/no-neck-pain.txt, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, tests/test_integrations.lua
saving state after important executions prevent inconsistencies when accessing it, this will also allowing introducing debouncing at any time of the plugin toggling, which might help for https://github.com/shortcuts/no-neck-pain.nvim/issues/221 and https://github.com/shortcuts/no-neck-pain.nvim/issues/227
=> chore: save state consistency

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/util/api.lua, tests/helpers.lua, tests/test_API.lua, tests/test_autocmds.lua, tests/test_buffers.lua, tests/test_colors.lua, tests/test_commands.lua, tests/test_integrations.lua, tests/test_mappings.lua, tests/test_options.lua, tests/test_scratchpad.lua, tests/test_splits.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/258
we had to introduce debounce because `TSPlaygroundToggle` outcome being inconsistent due to `nvim-treesitter/playground` closing/creating many buffers at start up, but if instead we debounce just by a few (2) milliseconds each step of the `NoNeckPain` lifecycle, we can prevent flickering and state inconsistencies
this also fixes NvimTree race conditions with NoNeckPain!!
=> fix: flickering because of debounce

.github/workflows/main.yml, .gitignore, .luacheckrc, .luarc.json, Makefile, tests/test_buffers.lua
[trying out recommendations](https://www.reddit.com/r/neovim/comments/1bfdp9m/comment/kv2ljvo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
=> chore: add luals check on ci

.github/workflows/main.yml, Makefile, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, scripts/init_with_neotest.lua, scripts/init_with_nvimdapui.lua, tests/test_commands.lua, tests/test_integrations.lua
close https://github.com/shortcuts/no-neck-pain.nvim/issues/258
An integration will always try to open their window on the further side of the screen, so we can actually on force no-neck-pain to close/reopen the integration at the first start (when side buffer don't exist yet)
_this solution is a bit more complicated but safest_
=> feat(integrations): skip redraw on every calls

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, tests/test_API.lua, tests/test_autocmds.lua
close https://github.com/shortcuts/no-neck-pain.nvim/issues/306
add a new `autocmds` option named `skipEnteringNoNeckPainBuffer` (went super explicit to let the user know it only triggers on no-neck-pain buffers) which, when `true`, skips entering a side buffer until it finds a valid one in the list of opened windows.
The option defaults to `false`
=> feat(api): add autocmd to skip entering side buffer

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, tests/test_autocmds.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/306
- as per https://github.com/shortcuts/no-neck-pain.nvim/issues/306#issuecomment-2016527050 listen to `WinLeave` instead of `WinEnter` in order to execute the re-routing  a bit earlier
- determine if we don't re-route to an other side buffer so that we don't end up triggering the command twice
- do not register the autocmds if scratchPads are enabled
=> fix(autocmds): buffer rerouting and with scratchPads

lua/no-neck-pain/main.lua
scratchPads can be enabled on toggle, meaning that we should register the autocmd even with scratchPads enabled and determine if we should skip the re-routing at the autocmd level
=> fix(autocmds): allow registering rerouting for toggle option

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, tests/test_autocmds.lua
since debouncing has been globally introduced, the autocmd clear wasn't kicking in anymore as the state was still nil, we know wait 20ms before clearing
=> fix(autocmds): clear after debounce

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/wins.lua
we should check for the current state of the scratchPad instead of the configuration value, so that we don't end up with unsync'd conditions
=> fix(autocmds): better state check for scratchpads

README.md, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/wins.lua, tests/test_autocmds.lua, tests/test_mappings.lua, tests/test_scratchpad.lua
It's hard to compose a scratchpad file location today, it requires 3 props to determine the full `pathToFile` and the custom filetype doesn't work everytime.
The idea is to propose a single property that does it all, which will deprecate all the other options in the next major
before, in order to define custom buffers
```lua
buffers = {
left = {
bo = {
filetype = "custom"
},
scratchPad = {
enabled = true,
fileName = "notes",
location = "~/Documents"
},
},
right = {
bo = {
filetype = "md"
},
scratchPad = {
enabled = true,
fileName = "foo",
location = "./bar/baz"
},
},
},
```
now
```lua
buffers = {
left = {
bo = {
filetype = "custom"
},
scratchPad = {
enabled = true,
pathToFile = "~/Documents/notes.custom"
},
},
right = {
scratchPad = {
enabled = true,
pathToFile = "./bar/baz/foo.md"
},
}, …
```
=> feat(scratchPad): provide `pathToFile` option

lua/no-neck-pain/wins.lua, tests/test_scratchpad.lua
the default scratchPad options should override the neovim ones to make the buffers usable
=> fix(scratchPad): option defined in wrong order

Makefile, README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/util/constants.lua, scripts/init_with_outline.lua, tests/test_API.lua, tests/test_integrations.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/296
=> feat(integrations): support outline.nvim

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, tests/test_autocmds.lua, tests/test_integrations.lua
on vim enter, the group for auto-enabling wasn't cleared, meaning the plugin would re-enable everytime a new buffer was entered
=> fix(autocmds): wrong registered group

lua/no-neck-pain/main.lua, lua/no-neck-pain/wins.lua, tests/test_API.lua
we were force closing remaining windows on teardown but it's possible that the buffer isn't yet saved, we therefore need to replicate this behavior
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/348
=> fix(autocmds): do not force close unsaved buffers

Makefile, lua/no-neck-pain/main.lua, scripts/init_with_incline.lua, tests/test_API.lua
relative windows are considered as windows, so the disable check was false in case one is opened
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/352
=> fix(disable): prevent blocked quit with relative windows

Makefile, scripts/clone_deps.sh, scripts/reset_deps_at_date.sh, tests/test_API.lua
https://github.com/echasnovski/mini.nvim/commit/dbea32594cb644d6a78da50d156f66a56096942c?diff=split&w=1 introduces a breaking change but I'm not yet sure what's required to make it work like before
=> chore: pin mini.nvim version before bc

Makefile, lua/no-neck-pain/colors.lua, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/util/api.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/wins.lua, scripts/init_with_aerial.lua, scripts/init_with_neotree.lua, scripts/init_with_nvimdapui.lua, scripts/init_with_tsplayground.lua, scripts/minimal_init.lua, tests/helpers.lua, tests/test_API.lua, tests/test_autocmds.lua, tests/test_commands.lua, tests/test_integrations.lua, tests/test_mappings.lua, tests/test_options.lua, tests/test_splits.lua, tests/test_tabs.lua
the custom logic for vsplit handling has reached its limits, it's now impossible to handle every edge cases and might make the user experience clunky.
This winlayout refactoring aims at increasing consistency by considering nvim as the source of truth, as it should be. Leveraging also allows the plugin to avoid debouncing and concurrent refreshes in order to wait for the ui to be refreshed, we can now just evaluate the API instantly.
This also unlocks nnp buffers to be CONSISTENTLY on both sides, where they should always be.
supersede https://github.com/shortcuts/no-neck-pain.nvim/pull/374
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/368
=> feat(splits): leverage winlayout

scripts/init_with_aerial.lua, scripts/init_with_tsplayground.lua, tests/helpers.lua, tests/test_API.lua, tests/test_autocmds.lua, tests/test_buffers.lua, tests/test_colors.lua, tests/test_commands.lua, tests/test_integrations.lua, tests/test_mappings.lua, tests/test_options.lua, tests/test_scratchpad.lua, tests/test_splits.lua, tests/test_tabs.lua
use a more idiomatic solution for test helpers rather than re-importing the helper module
=> chore: rework test helpers

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/util/event.lua, lua/no-neck-pain/wins.lua, tests/test_splits.lua
should close https://github.com/shortcuts/no-neck-pain.nvim/issues/298
opening/closing a vsplit alters the ui, and since we resize side buffers, it might shrink buffers that are on the side of those sides.
we now resize splits as well, but not integrations
=> fix: inconsistent resizes on vsplits

lua/no-neck-pain/util/constants.lua
I use mini.starter as a dashboard and I enjoy your plugin very much. This fixes the integration between them.
Thanks for reviewing!
Before change:
After change:
=> feat: add mini.starter dashboard to constants

lua/no-neck-pain/main.lua, lua/no-neck-pain/wins.lua, tests/test_buffers.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/385
the default filetype should be set, and skipped only if the scratchpad is enabled
=> fix: default filetype not set

lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/ui.lua, scripts/init_with_tsplayground.lua, tests/test_integrations.lua, tests/test_splits.lua
rework the way we compute the size of side buffers by properly assessing the number of valid sides, which was causing weird layout when 2 were actives.
also resize the vsplits based on the layout, rather than guessing which windows are vsplits, this allows a super consistent ui layout
todo: closing an integration doesn't restore the position of the `curr` buffer, but the width is correct
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/389
=> fix(split): vsplits integration resize inconsistencies

lua/no-neck-pain/main.lua, lua/no-neck-pain/ui.lua, lua/no-neck-pain/util/api.lua, tests/test_autocmds.lua
When having only one side, and a full width split focused (e.g. quickfix list, help), using `<C-w>w` to go to the next window brings us to the full width split, instead of going to the next available window.
=> fix(autocmds): prevent stucked focus on skip enter

lua/no-neck-pain/ui.lua
we should pre-compute the side width, otherwise when computing `right`, `left` will already be there and make the computing off by left's width
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/396
=> fix(buffers): compute width before creating sides

doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, tests/test_integrations.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/400
This legacy assertion is not relevant anymore, we only care about if it's left or right now, the other positions are ignored
=> fix(integrations): do not assert position

lua/no-neck-pain/util/api.lua
Related discussion: #414 
Normally, windows created with `focusable = false` cannot be focused by user interactions. However, the current logic for skipping past side buffers can cause such a window to become focused.
This change makes it so that only focusable windows are considered as skip targets.
=> fix: prevent non-focusable windows from being focused

.github/workflows/main.yml, lua/no-neck-pain/main.lua, tests/test_autocmds.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/415
we assume the window list is valid, but in case of `bd`, it actually deletes the window, which then makes the plugin fallback to a new set of window
we should make sure the window is valid before actually rerouting
=> fix: do not reroute to invalid (deleted) window

lua/no-neck-pain/ui.lua, scripts/init_auto_open.lua, tests/test_colors.lua
Please see https://github.com/shortcuts/no-neck-pain.nvim/issues/430
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/430
none
=> fix: 'Invalid window id ...' error when restoring a session saved with an invisible Scratch Window (#430)

Makefile, README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/main.lua, scripts/init_callbacks.lua, tests/test_API.lua, tests/test_callbacks.lua, tests/test_integrations.lua
This PR is a follow up of https://github.com/shortcuts/no-neck-pain.nvim/pull/448, closes https://github.com/shortcuts/no-neck-pain.nvim/issues/111
----
This is for the feature mentioned in #111, or at least some of it: User can specify callbacks in the config, that will run before and after the buffer is centered or restored. Nothing happens by default.
Callbacks take no arguments, because I don't know what values exist that would be useful to the user.
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/111
For example, to disable the individual status line, and hide the command line, but restore both options when toggling this plugin off:
```lua
require("no-neck-pain").setup({
-- Some options ...
callbacks = {
preEnable = function()
vim.opt.laststatus = 0
vim.opt.cmdheight  = …
```
=> feat: provide pre/post enable and pre/post disable callback methods

README.md, doc/no-neck-pain.txt, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/455
commands like `nvim +line file` are executed once nvim has been entered, which is similar to dashboard plugins executing things once entered.
using such commands or dashboards can create race conditions with how we shift windows around, `enableOnVimEnter` now allows `"safe"` to be provided, which debounces enabling the plugin until we found a suitable time (e.g. when other plugins have executed)
this however creates a small (few ms) layout shift that could be noticeable
=> feat: allow safe `enableOnVimEnter`

lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, tests/test_options.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/449
when creating a new window from neovim/vim commands, it uses `win_alloc` (https://github.com/neovim/neovim/blob/master/src/nvim/window.c#L5127) which copies the currently focused window option, which leads to this issue of line number disappearing because the last opened window is a side buffer, that has different window option.
sadly, `win_alloc_first` (https://github.com/neovim/neovim/blob/master/src/nvim/window.c#L4052) isn't publicly exposed, so the only solution is to copy the user's window option at startup
=> fix: properly reset window options on `bd`

lua/no-neck-pain/init.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/ui.lua, lua/no-neck-pain/util/event.lua, scripts/init_with_nvimtree.lua, scripts/init_with_outline.lua, scripts/init_with_tsplayground.lua, tests/helpers.lua, tests/test_integrations.lua, tests/test_splits.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/467
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/453
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/450
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/411
we shouldn't have to resize the integrations, since we compute the width of a side based on the width of the integration
=> fix: do not resize integration windows

Makefile, doc/no-neck-pain.txt, doc/tags, lua/no-neck-pain/config.lua, lua/no-neck-pain/init.lua, lua/no-neck-pain/main.lua, lua/no-neck-pain/state.lua, lua/no-neck-pain/ui.lua, plugin/no-neck-pain.lua, tests/helpers.lua, tests/test_API.lua, tests/test_autocmds.lua, tests/test_buffers.lua, tests/test_integrations.lua, tests/test_mappings.lua, tests/test_options.lua, tests/test_splits.lua, tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/453
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/470
the width of an integration doesn't need to be accounted as a vsplit occupied width, but should rather just be deduced from the remaining width for the side buffers
=> fix: properly compute remaining width after integrations

lua/no-neck-pain/main.lua
when enabling the scratch pad, we restore the focus to the previously focused window, however disabling it doesn't restore it.
this pr now properly restores the focus so that the cursor doesn't stay on the unusable side buffer
=> fix(scratchPad): restore focus when disabling

lua/no-neck-pain/config.lua
the early return to skip mappings (when false/nil is provided) would cause the subsequent mappings to be skipped as well, wrapping the if clause is enough to skip the disabled ones
=> fix(mappings): race conditions

lua/no-neck-pain/colors.lua, lua/no-neck-pain/state.lua, tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/494
it is currently not (easily) possible to provide custom highlight groups to the no-neck-pain windows without playing with the nvim api. This PR adds default namespace and groups tied to the no-neck-pain windows so that one can easily link custom highlights to it.
also drop support fold old apis
=> feat(highlight): create namespace and empty groups by default
