- lua/no-neck-pain/config.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/2
> feat: split screen support

- .github/workflows/main.yml
- Makefile
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util.lua
- plugin/no-neck-pain.lua
- scripts/minimal_init.lua
- scripts/minitest.lua
- stylua.toml
- tests/helpers.lua
- tests/test_API.lua
- tests/test_OK.lua
following recommendations from https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-test.md, tries to set up tests
> feat: add tests

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/11
> fix: prevent float window to kill side buffers

- README.md
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/main.lua
- tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/10
> feat: left buffer only option

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/14
> feat: disable NNP when killing side buffers

- README.md
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/23
> docs: add wiki

- README.md
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/main.lua
- tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/15
> feat(api)!: make API extensible

- README.md
follow up of https://github.com/shortcuts/no-neck-pain.nvim/pull/28
> chore: recommend latest stable tag for `vim-plug`

- Makefile
- doc/no-neck-pain.txt
- doc/tags
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util.lua
- scripts/minimal_init.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/30
> docs: generate documentation

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- tests/test_API.lua
> docs(README): misspelled api

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/35
> fix: remove event redundancy

- README.md
- tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/43
> chore: document simpler usage

- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/color.lua
- tests/helpers.lua
- tests/test_API.lua
- tests/test_side_buffers.lua
> chore: make tests less redundant

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/util/color.lua
- tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/56
> feat: add `rose-pine` color themes

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/55
> chore: add issue and PR templates

- .chglog/template.md
- CHANGELOG.md
solves one part of https://github.com/shortcuts/no-neck-pain.nvim/issues/53
> chore: changelog with author

- README.md
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/68
> chore: add motivations to README

- README.md
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/84
> chore: add lazy.nvim snippet to README.md

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/color.lua
- lua/no-neck-pain/util/debug.lua
- lua/no-neck-pain/util/event.lua
- lua/no-neck-pain/util/win.lua
Remove some of the unused internal login, along with using format directly in the `D.print` method.
There is still too much log IMO but we could start removing some once we add more tests
> chore: better debug logging

- README.md
> chore: add features to README.md

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
This aims at make the option list more readable
> chore: more readable configuration section

- Makefile
- scripts/release.sh
Small script to ease the release process
> feat: add release script

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- tests/helpers.lua
- tests/test_API.lua
This mapping option allow to enable and disable the plugin by pressing `<Leader>np` by default, it's possible to disable it by passing `false` to the option, or provide your own binding.
> feat: add `toggleMapping` option

- .github/workflows/main.yml
- Makefile
- tests/helpers.lua
- tests/test_API.lua
> chore: more CI checks

- README.md
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/util/color.lua
- tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/64
adds new theme variants for https://github.com/projekt0n/github-nvim-theme and also make it easier to register new integrations
> feat: add more default themes

- .github/workflows/main.yml
- tests/test_API.lua
nightly is now reusable on the CI :D
> chore: add nightly to the CI

- lua/no-neck-pain/config.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/color.lua
- lua/no-neck-pain/util/map.lua
- lua/no-neck-pain/util/split.lua
- lua/no-neck-pain/util/state.lua
- lua/no-neck-pain/util/trees.lua
- tests/helpers.lua
- tests/test_API.lua
- tests/test_autocmd.lua
- tests/test_buffers.lua
- tests/test_split.lua
Some internal dx improvement and cleanup of unused methods.
> chore: some dx improvements

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/event.lua
- lua/no-neck-pain/util/state.lua
small cleanup of the state and skip event
> chore: prepare `tabs`

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/split.lua
- lua/no-neck-pain/util/state.lua
- lua/no-neck-pain/util/win.lua
follow up of https://github.com/shortcuts/no-neck-pain.nvim/pull/149, this PR imports some changes from [the `feat/tabs` branch](https://github.com/shortcuts/no-neck-pain.nvim/pull/150) to ease navigating through meaningful changes.
> chore: prepare `tabs` (p2)

- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/event.lua
the color group of the right buffer was never deleted due to a typo.
> fix: right color group never deleted

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- mention tabs support in the readme
- small description improvement
> chore: update README.md

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- plugin/no-neck-pain.lua
- tests/test_API.lua
- tests/test_commands.lua
- tests/test_mapping.lua
This PR provides new up and down commands and mappings to easily resize the current window.
> feat: add up/down commands and mappings

- .github/workflows/main.yml
re-enable nightly and upgrade to latest version.
> chore: nightly and 0.8.3 ci

- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/wins.lua
discovered in https://github.com/shortcuts/no-neck-pain.nvim/pull/180
This PR fixes a few unexpected event trigger.
> fix: events triggering multiple times

- lua/no-neck-pain/tabs.lua
- lua/no-neck-pain/trees.lua
- lua/no-neck-pain/util/constants.lua
- lua/no-neck-pain/util/debug.lua
- lua/no-neck-pain/util/event.lua
- lua/no-neck-pain/wins.lua
project gets bigger and time flies so let's make sure I forget nothing :D
> chore: add some internal documentation

- lua/no-neck-pain/color.lua
- lua/no-neck-pain/tabs.lua
- lua/no-neck-pain/util/event.lua
- lua/no-neck-pain/wins.lua
- tests/test_colors.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/184
we might fall in the nil background case even when custom background is defined, this should cover this case.
> fix: transparent background with custom backgroundColor

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/tabs.lua
- lua/no-neck-pain/trees.lua
- lua/no-neck-pain/wins.lua
- tests/test_API.lua
- tests/test_integrations.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/191
This PR adds support for https://github.com/nvim-neo-tree/neo-tree.nvim as part of the integrations process.
> feat: support neo-tree

- lua/no-neck-pain/trees.lua
small improvement to easily register integrations.
> chore: easier registrations of integrations

- .github/workflows/main.yml
- README.md
> chore: update CI nvim versions

- lua/no-neck-pain/colors.lua
- tests/test_API.lua
- tests/test_autocmds.lua
- tests/test_buffers.lua
- tests/test_colors.lua
- tests/test_integrations.lua
- tests/test_mappings.lua
- tests/test_scratchpad.lua
- tests/test_splits.lua
I'm introducing some refactors in https://github.com/shortcuts/no-neck-pain.nvim/issues/241, but the current testing strategy makes it hard to determine if there will be side effects.
To give more confidence, we can assert the whole scope instead of a single property.
> chore(tests): better assertions

- tests/helpers.lua
- tests/test_API.lua
- tests/test_autocmds.lua
- tests/test_buffers.lua
- tests/test_colors.lua
- tests/test_commands.lua
- tests/test_integrations.lua
- tests/test_mappings.lua
- tests/test_options.lua
- tests/test_scratchpad.lua
- tests/test_splits.lua
- tests/test_tabs.lua
not sure why I did this test helper aliasing in the first place, it's super annoying to iterate with it
> chore: rewrite tests helpers

- .github/workflows/main.yml
- Makefile
- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
deps upgrade and scripts cleanup
> chore: deps and cleanup

- .gitignore
- lua/no-neck-pain/colors.lua
- lua/no-neck-pain/state.lua
- lua/no-neck-pain/util/constants.lua
- lua/no-neck-pain/util/event.lua
- tests/test_API.lua
- tests/test_colors.lua
- tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/314
> feat(integrations): support alpha.nvim

- Makefile
> chore(mini.nvim): use stable version

- .github/workflows/main.yml
> chore: run on nvim 10

- .github/workflows/main.yml
will investigate later why nightly hangs
> chore: continue-on-error for nightly

- Makefile
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/util/constants.lua
- scripts/init_with_aerial.lua
- scripts/init_with_tsplayground.lua
- tests/test_API.lua
- tests/test_integrations.lua
- tests/test_tabs.lua
allow side buffers to be opened when aerial.nvim is open
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/359
> feat(integrations): support aerial.nvim

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/util/api.lua
- tests/test_API.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/363
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/358
> feat(disable): warns with better ux when trying to leave

- lua/no-neck-pain/main.lua
- tests/test_tabs.lua
close https://github.com/shortcuts/no-neck-pain.nvim/issues/370
we do not account for remaining tabs when determining if we should quit nvim or just disable the plugin
> fix(tabs): do not close if tabs are left

- doc/no-neck-pain.txt
- lua/no-neck-pain/colors.lua
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/state.lua
- lua/no-neck-pain/util/api.lua
- lua/no-neck-pain/util/debug.lua
- lua/no-neck-pain/util/event.lua
- lua/no-neck-pain/wins.lua
- tests/helpers.lua
- tests/test_API.lua
- tests/test_mappings.lua
- tests/test_splits.lua
- tests/test_tabs.lua
because this is more lua idiomatic and also helps with readability
> chore: camel case to snake case

- .github/workflows/main.yml
- Makefile
- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/colors.lua
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/init.lua
- lua/no-neck-pain/main.lua
- lua/no-neck-pain/state.lua
- lua/no-neck-pain/ui.lua
- lua/no-neck-pain/util/api.lua
- lua/no-neck-pain/util/constants.lua
- lua/no-neck-pain/util/debug.lua
- lua/no-neck-pain/util/event.lua
- lua/no-neck-pain/wins.lua
- plugin/no-neck-pain.lua
- tests/helpers.lua
- tests/test_API.lua
- tests/test_autocmds.lua
- tests/test_integrations.lua
- tests/test_options.lua
- tests/test_splits.lua
- tests/test_tabs.lua
This PR prepares the release of the new major version, see https://github.com/shortcuts/no-neck-pain.nvim/issues/361 for the detailed additions.
If you encounter any bug, I encourage you to [report them](https://github.com/shortcuts/no-neck-pain.nvim/issues/new?assignees=&labels=&projects=&template=Bug_report.md) but if you are lazy, you can use the [frozen stable](https://github.com/shortcuts/no-neck-pain.nvim/tree/1.x) in the meantime, see [installation guide](https://github.com/shortcuts/no-neck-pain.nvim/tree/1.x?tab=readme-ov-file#-installation).
close https://github.com/shortcuts/no-neck-pain.nvim/issues/361
close https://github.com/shortcuts/no-neck-pain.nvim/issues/353
close https://github.com/shortcuts/no-neck-pain.nvim/issues/277
close …
> feat(next)!: 2.0.0 major version

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
contributes to https://github.com/shortcuts/no-neck-pain.nvim/issues/426
updates the integrations documentation and the README
> docs: update integration docs and refresh README.md

- lua/no-neck-pain/init.lua
close https://github.com/shortcuts/no-neck-pain.nvim/issues/433
> fix(autocmds): BufWinEnter race condition?

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/init.lua
- lua/no-neck-pain/util/api.lua
- lua/no-neck-pain/util/constants.lua
- lua/no-neck-pain/util/event.lua
- tests/test_API.lua
- tests/test_integrations.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/441
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/437
this pr adds an opt-in configuration field under `integrations` to hint the plugin to debounce the opening of the side buffers.
> feat: better dashboard support

- .github/workflows/main.yml
> chore: test on nvim 11

- README.md
- doc/no-neck-pain.txt
- lua/no-neck-pain/config.lua
- lua/no-neck-pain/init.lua
- tests/test_integrations.lua
I added support for custom dashboard to debounce the plugin but actually forgot to use it
> fix: allow custom dashboards

- lua/no-neck-pain/config.lua
- tests/test_integrations.lua
reported here https://github.com/shortcuts/no-neck-pain.nvim/commit/289bc6d5693feff6b952fc534cbfc8f00c44545d#commitcomment-156000380, thanks a lot @nickvonkaenel
> fix: npe on dashboard's filetypes

- lua/no-neck-pain/main.lua
- tests/test_tabs.lua
closes https://github.com/shortcuts/no-neck-pain.nvim/issues/473
> fix: prevent unexpected error on resize for unknown tabs

- lua/no-neck-pain/main.lua
- lua/no-neck-pain/state.lua
some leftover from previous iterations
> chore: cleanup unused state functions

- README.md
Hello! Just a quick add to the README for the new way to install No Neck Pain for those who use Nixvim.
> docs: Add Nixvim installation snippet to README.md
